---
# Default values for univention-management-console-gateway
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Global values
affinity: {}
environment: {}
fullnameOverride: ""
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
tolerations: []


# -- Application configuration of the Univention Management Console Gateway
umcGateway:
  # -- Domain name of the instance.
  # Example: `example.org`
  domainname: null
  # -- Host name of the instance.
  # Example: `souvap`
  hostname: null
  # -- The FQDN of the identity provider.
  # Example: `https://id.souvap.example.org`
  ssoFqdn: null


## Kubernetes ingress
ingress:
  # -- Set this to `true` in order to enable the installation on Ingress related objects.
  enabled: false
  ingressClassName: "nginx"
  # -- The hostname. This parameter has to be supplied. Example `portal.example`.
  host: null
  # -- The path configuration. The default only grabs what is handled by the UMC gateway.
  paths:
    - pathType: Prefix
      path: /univention/(js|languages.json|login|management|meta.json|theme.css|themes($/.*))
  tls:
    enabled: true
    secretName: ""


## Istio support
istio:
  # -- Set this to `true` in order to enable the installation on Istio related objects.
  enabled: true
  # -- The hostname. This parameter has to be supplied. Example `portal.example`.
  host: null
  virtualService:
    enabled: true
    annotations: {}
    # -- The paths configuration.
    # The default only grabs what is known to be handled by the UMC gateway.
    paths:
      - match: "prefix"
        path: "/univention/js/"
        rewrite: "/univention/js/"
      - match: "prefix"
        path: "/univention/languages.json"
        rewrite: "/univention/languages.json"
      - match: "prefix"
        path: "/univention/login/"
        rewrite: "/univention/login/"
      - match: "prefix"
        path: "/univention/management/"
        rewrite: "/univention/management/"
      - match: "prefix"
        path: "/univention/meta.json"
        rewrite: "/univention/meta.json"
      - match: "prefix"
        path: "/univention/theme.css"
        rewrite: "/univention/theme.css"
      - match: "prefix"
        path: "/univention/themes/"
        rewrite: "/univention/themes/"
  gateway:
    enabled: false
    annotations:
    selectorIstio: "ingressgateway"
    externalGatewayName: "swp-istio-gateway"
    tls:
      enabled: true
      httpsRedirect: true
      secretName: ""


## Docker image
image:
  registry: "registry.souvap-univention.de"
  repository: "souvap/tooling/images/univention-management-console/umc-gateway"
  imagePullPolicy: "Always"
  tag: "latest"

  ## Define image sha256 as an alternative to `tag`
  # sha256:


## Container deployment probes
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 3
    periodSeconds: 30
    failureThreshold: 3
    successThreshold: 1

  readiness:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 15
    failureThreshold: 30
    successThreshold: 1


## Deployment resources
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "4Gi"
    cpu: "4"


## Kubernetes Service
service:
  enabled: true
  type: "ClusterIP"
  ports:
    http:
      containerPort: 80
      port: 80
      protocol: "TCP"

  sessionAffinity:
    enabled: false
    timeoutSeconds: 10800

...
