---

version: '3.8'

services:
  gateway:
    build:
      context: ./images/gateway
      args:
        DOCKER_REGISTRY: artifacts.knut.univention.de/dockerhub_proxy_cache/library/
        LABEL_CREATED: "${CI_JOB_STARTED_AT}"
        LABEL_REVISION: "${CI_COMMIT_SHA}"
        LABEL_SOURCE: "${CI_PROJECT_URL}"
        LABEL_VERSION: "${CI_PIPELINE_ID}"

  server:
    build:
      context: ./images/server
      args:
        DOCKER_REGISTRY: artifacts.knut.univention.de/dockerhub_proxy_cache/library/
        LABEL_CREATED: "${CI_JOB_STARTED_AT}"
        LABEL_REVISION: "${CI_COMMIT_SHA}"
        LABEL_SOURCE: "${CI_PROJECT_URL}"
        LABEL_VERSION: "${CI_PIPELINE_ID}"

  web:
    build:
      context: ./images/web
      args:
        DOCKER_REGISTRY: artifacts.knut.univention.de/dockerhub_proxy_cache/library/
        LABEL_CREATED: "${CI_JOB_STARTED_AT}"
        LABEL_REVISION: "${CI_COMMIT_SHA}"
        LABEL_SOURCE: "${CI_PROJECT_URL}"
        LABEL_VERSION: "${CI_PIPELINE_ID}"

...
