---

version: '3.8'

services:
  server:
    image: umc-server
    build:
      context: ./images/server
    env_file: .env.server

  web:
    image: umc-web
    build:
      context: ./images/web
    env_file: .env.web

...
