---

version: '3.8'

services:
  server:
    build:
      context: ./images/server
      args:
        DOCKER_REGISTRY: artifacts.knut.univention.de/dockerhub_proxy_cache/library/

  web:
    build:
      context: ./images/web
      args:
        DOCKER_REGISTRY: artifacts.knut.univention.de/dockerhub_proxy_cache/library/

...
