# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---

services:
  umc-gateway:
    build:
      context: ./docker/gateway
      platforms:
        # FIXME: remove once arm64 packages are available at updates.software-univention.de
        - "linux/amd64"
      target: final
  umc-server:
    build:
      context: ./docker/server
      platforms:
        # FIXME: remove once arm64 packages are available at updates.software-univention.de
        - "linux/amd64"
      target: final
...
