---

# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | quote }}
        checksum/secret: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- if or .Values.imagePullSecrets .Values.global.imagePullSecrets  }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
        {{- range .Values.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      containers:
        - name: {{ include "common.names.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "global" .Values.global ) | quote }}
          {{- with .Values.image }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          env:
            - name: "SELF_SERVICE_DB_SECRET"
              valueFrom:
                secretKeyRef:
                  {{- if .Values.umcServer.postgresqlCredentialSecret.name }}
                  name: {{ printf "%s-volume" .Values.umcServer.postgresqlCredentialSecret.name }}
                  key: {{ .Values.umcServer.postgresqlCredentialSecret.key }}
                  {{- else }}
                  name: {{ include "common.names.fullname" . }}
                  key: "db_password"
                  {{- end }}
            - name: "SELF_SERVICE_MEMCACHED_SECRET"
              valueFrom:
                secretKeyRef:
                  {{- if .Values.umcServer.memcachedCredentialSecret.name }}
                  name: {{ printf "%s-volume" .Values.umcServer.memcachedCredentialSecret.name | quote }}
                  key: {{ .Values.umcServer.memcachedCredentialSecret.key | quote }}
                  {{- else }}
                  name: {{ include "common.names.fullname" . }}
                  key: "memcached_password"
                  {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "common.names.fullname" . }}
          volumeMounts:
            {{- if .Values.extraVolumeMounts }}
            {{ toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
            {{- if .Values.mountUcr }}
            - name: "config-map-ucr-defaults"
              mountPath: "/etc/univention/base-defaults.conf"
              subPath: "base.conf"
            {{- end }}
            {{- if (include "udm-rest-api.configMapUcr" .) }}
            - name: "config-map-ucr"
              mountPath: "/etc/univention/base.conf"
              subPath: "base.conf"
            {{- end }}
            {{- if (include "udm-rest-api.configMapUcrForced" .) }}
            - name: "config-map-ucr-forced"
              mountPath: "/etc/univention/base-forced.conf"
              subPath: "base.conf"
            {{- end }}
            {{- if .Values.mountSecrets }}
            - name: "secrets"
              mountPath: "{{ .Values.umcServer.secretMountPath }}"
            {{- else }}
            {{- if .Values.umcServer.ldapCredentialSecret.name }}
            - name: {{ printf "%s-volume" .Values.umcServer.ldapCredentialSecret.name | quote }}
              mountPath: "{{ .Values.umcServer.secretMountPath }}/ldap_secret"
              subPath: {{ .Values.umcServer.ldapCredentialSecret.ldapPasswordKey | quote }}
              readOnly: true
            - name: {{ printf "%s-volume" .Values.umcServer.ldapCredentialSecret.name | quote }}
              mountPath: "{{ .Values.umcServer.secretMountPath }}/machine_secret"
              subPath: {{ .Values.umcServer.ldapCredentialSecret.machinePasswordKey | quote }}
              readOnly: true
            {{- end }}
            {{- if .Values.umcServer.smtpCredentialSecret.name }}
            - name: {{ printf "%s-volume" .Values.umcServer.smtpCredentialSecret.name | quote }}
              mountPath: "{{ .Values.umcServer.secretMountPath }}/smtp_secret"
              subPath: {{ .Values.umcServer.smtpCredentialSecret.key | quote }}
              readOnly: true
            {{- end }}
            {{- if .Values.umcServer.postgresqlCredentialSecret.name }}
            - name: {{ printf "%s-volume" .Values.umcServer.postgresqlCredentialSecret.name | quote }}
              mountPath: "{{ .Values.umcServer.secretMountPath }}/db_password"
              subPath: {{ .Values.umcServer.postgresqlCredentialSecret.key | quote }}
              readOnly: true
            {{- end }}
            {{- if .Values.umcServer.memcachedCredentialSecret.name }}
            - name: {{ printf "%s-volume" .Values.umcServer.memcachedCredentialSecret.name | quote }}
              mountPath: "{{ .Values.umcServer.secretMountPath }}/memcached_password"
              subPath: {{ .Values.umcServer.memcachedCredentialSecret.key | quote }}
              readOnly: true
            {{- end }}
            {{- end }}
          ports:
            {{- range $key, $value := .Values.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $value.containerPort }}
              protocol: {{ $value.protocol }}
            {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            successThreshold: {{ .Values.probes.liveness.successThreshold }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
            successThreshold: {{ .Values.probes.readiness.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.extraVolumes }}
        {{ toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
        {{- if .Values.mountUcr }}
        - name: "config-map-ucr-defaults"
          configMap:
            name: {{ include "udm-rest-api.configMapUcrDefaults" . | quote }}
        {{- end }}
        {{- if (include "udm-rest-api.configMapUcr" .) }}
        - name: "config-map-ucr"
          configMap:
            name: {{ include "udm-rest-api.configMapUcr" . | quote }}
        {{- end }}
        {{- if (include "udm-rest-api.configMapUcrForced" .) }}
        - name: "config-map-ucr-forced"
          configMap:
            name: {{ include "udm-rest-api.configMapUcrForced" . | quote }}
        {{- end }}
        {{- if .Values.mountSecrets }}
        - name: "secrets"
          secret:
            secretName: {{ include "common.names.fullname" . | quote }}
        {{- else }}
        {{- if .Values.umcServer.ldapCredentialSecret.name }}
        - name: {{ printf "%s-volume" .Values.umcServer.ldapCredentialSecret.name | quote }}
          secret:
            secretName: {{ .Values.umcServer.ldapCredentialSecret.name | quote }}
        {{- end }}
        {{- if .Values.umcServer.smtpCredentialSecret.name }}
        - name: {{ printf "%s-volume" .Values.umcServer.smtpCredentialSecret.name | quote }}
          secret:
            secretName: {{ .Values.umcServer.smtpCredentialSecret.name | quote }}
        {{- end }}
        {{- if .Values.umcServer.postgresqlCredentialSecret.name }}
        - name: {{ printf "%s-volume" .Values.umcServer.postgresqlCredentialSecret.name | quote }}
          secret:
            secretName: {{ .Values.umcServer.postgresqlCredentialSecret.name | quote }}
        {{- end }}
        {{- if .Values.umcServer.memcachedCredentialSecret.name }}
        - name: {{ printf "%s-volume" .Values.umcServer.memcachedCredentialSecret.name | quote }}
          secret:
            secretName: {{ .Values.umcServer.memcachedCredentialSecret.name | quote }}
        {{- end }}
        {{- end }}
