{{/*
SPDX-FileCopyrightText: 2024 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

---
kind: "Secret"
apiVersion: "v1"
type: "kubernetes.io/basic-auth"
metadata:
  name: {{ include "common.names.fullname" . }}-smtp
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
    dev: mark
  {{- if .Values.additionalAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
stringData:
  # NOTE: Username should be in here, but UMC is not able to use it from here at
  # the moment.
  username: {{ .Values.smtp.auth.username | quote }}
  password: {{ .Values.smtp.auth.password | quote }}

...
