{{/*
SPDX-FileCopyrightText: 2024 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

# NOTE: We may need a utility function, so that it is easy to handle corner
# cases correctly.
{{- if (not (coalesce .Values.ldap.auth.existingSecret.name .Values.global.ldap.auth.existingSecret.name )) }}
---
kind: "Secret"
apiVersion: "v1"
type: "Opaque"
metadata:
  name: {{ include "common.names.fullname" . }}-ldap
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
    dev: mark
  {{- if .Values.additionalAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
stringData:
  bindDn: {{ coalesce .Values.ldap.auth.bindDn .Values.global.ldap.auth.bindDn | quote }}
  password: {{ coalesce .Values.ldap.auth.password .Values.global.ldap.auth.password | quote }}

{{- end }}
