---
{{ include "common.configMap" (dict "top" . "overrides" "umc-gateway.configMap") }}

{{- define "umc-gateway.configMap" }}
{{- with .top }}
data:
  DOMAINNAME: "{{ .Values.umcGateway.domainname }}"
  HOSTNAME: "{{ .Values.umcGateway.hostname }}"
  SSO_FQDN: {{ required "The parameter \"umcGateway.ssoFqdn\" is required." .Values.umcGateway.ssoFqdn | quote }}
  SHOW_COOKIE_BANNER: "{{ .Values.umcGateway.showCookieBanner }}"
  COOKIE_BANNER_TITLE_DE: "{{ .Values.umcGateway.cookieBannerTitleDE }}"
  COOKIE_BANNER_TITLE_EN: "{{ .Values.umcGateway.cookieBannerTitleEN }}"
  COOKIE_BANNER_TEXT_DE: "{{ .Values.umcGateway.cookieBannerTextDE }}"
  COOKIE_BANNER_TEXT_EN: "{{ .Values.umcGateway.cookieBannerTextEN }}"
  SWP_APPLY_USABILITY_UI_PATCHES: "{{ .Values.umcGateway.swpApplyUsabilityUIPatches }}"
{{- end }}
{{- end }}
...
