---
{{ include "common.configMap" (dict "top" . "overrides" "umc-gateway.configMap") }}

{{- define "umc-gateway.configMap" }}
{{- with .top }}
data:
  UMC_HTML_TITLE: {{ .Values.umcGateway.umcHtmlTitle | default "Univention Management Console" | quote }}
{{- end }}
{{- end }}
...
