---
{{ include "common.configMap" (dict "top" . "overrides" "umc-gateway.configMap") }}

{{- define "umc-gateway.configMap" }}
{{- with .top }}
data:
  SWP_APPLY_USABILITY_UI_PATCHES: "{{ .Values.umcGateway.swpApplyUsabilityUIPatches }}"
{{- end }}
{{- end }}
...
