---
{{ include "common.deployment" (dict "top" . "overrides" "umc-gateway.deployment") }}
...

{{- define "umc-gateway.deployment" }}
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .top.Template.BasePath "/configmap.yaml") .top | sha256sum | quote }}
{{- end }}
