# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH

---

apiVersion: "v2"
type: "application"
name: "umc-server"
description: "A Helm chart for the Univention Management Console Server"
home: "https://www.univention.de/"

# Chart version
# Apply Semantic Versioning (https://semver.org/)
version: "0.34.3"

# UMC Version
appVersion: "12.0.29"

dependencies:
  - name: "nubus-common"
    version: "0.22.0"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
  - name: "postgresql"
    repository: "oci://docker.io/bitnamicharts"
    version: "^12.x.x"
    condition: "postgresql.bundled"
  - name: "memcached"
    repository: "oci://docker.io/bitnamicharts"
    version: "^7.x.x"
    condition: "memcached.bundled"

...
