---
{{ include "common.configMap" (dict "top" . "overrides" "umc-server.configMap") }}

{{- define "umc-server.configMap" }}
{{- with .top }}
data:
  LDAP_SECRET_FILE: "{{ .Values.umcServer.ldapSecretFile }}"
  MACHINE_SECRET_FILE: "{{ .Values.umcServer.machineSecretFile }}"
  PRIVATE_KEY_FILE: "{{ .Values.umcServer.privateKeyFile }}"
  CA_CERT_FILE: "{{ .Values.umcServer.caCertFile }}"
  CERT_PEM_FILE: "{{ .Values.umcServer.certPemFile }}"
{{- end }}
{{- end }}
...
