---
{{ include "common.secret" (dict "top" . "overrides" "umc-server.secret") }}

{{- define "umc-server.secret" }}
{{- with .top }}
data:
  ldap_secret: {{ .Values.umcServer.ldapSecret | quote }}
  machine_secret: {{ .Values.umcServer.machineSecret | quote }}
  ca_cert: {{ .Values.umcServer.caCert | quote }}
  cert_pem: {{ .Values.umcServer.certPem | quote }}
  private_key: {{ .Values.umcServer.privateKey | quote }}
{{- end }}
{{- end }}
