apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: '{{ include "common.names.fullname" . }}'
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  ldap_secret: {{ .Values.umcServer.ldapSecret | quote }}
  machine_secret: {{ .Values.umcServer.machineSecret | quote }}
  ca_cert: {{ .Values.umcServer.caCert | quote }}
  cert_pem: {{ .Values.umcServer.certPem | quote }}
  private_key: {{ .Values.umcServer.privateKey | quote }}
