---
- name: Fetch secrets from UCS machine
  hosts: ucs_primary

  tasks:
  - name: Fetch CAcert.pem
    ansible.builtin.fetch:
      src: /etc/univention/ssl/ucsCA/CAcert.pem
      dest: ../ssl/certs/CAcert.pem
      flat: true

  - name: Fetch cert.pem
    ansible.builtin.fetch:
      src: /etc/univention/ssl/{{ ansible_fqdn }}/cert.pem
      dest: ../ssl/certs/cert.pem
      flat: true

  - name: Fetch private.key
    ansible.builtin.fetch:
      src: /etc/univention/ssl/{{ ansible_fqdn }}/private.key
      dest: ../ssl/secret/private.key
      flat: true
