# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH

---

apiVersion: "v2"
type: "application"
name: "umc-gateway"
description: "A Helm chart for the Univention Management Console Gateway"
home: "https://www.univention.de/"
version: "0.1.0"

# UMC Version
appVersion: "12.0.29"

dependencies:
  - name: "nubus-common"
    # TODO: Replace with released version
    version: "0.20.0-pre-jbornhold-secrets-refactoring-tweaks-5"
    repository: "oci://artifacts.software-univention.de/nubus-dev/charts"
