# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH

---

apiVersion: "v2"
type: "application"
name: "umc-gateway"
description: "A Helm chart for the Univention Management Console Gateway"
home: "https://www.univention.de/"

# Chart version
# Apply Semantic Versioning (https://semver.org/)
version: "0.1.0"

# UMC Version
appVersion: "12.0.29"

dependencies:
  - name: "common"
    version: "^2.x.x"
    repository: "oci://registry-1.docker.io/bitnamicharts"

...
