# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH

---

# Stub values for running the Helm linter on the umc-gateway.
# Run it like this: helm lint -f values.yaml -f linter_values.yaml .

global:
  systemExtensions:
    - name: "portal"
      image:
        repository: "nubus/images/portal-extension"
        tag: "0.44.3@sha256:734efc0adda680526dde09387db964612f9e0ab020382580984488cc993c68f0"

ingress:
  enabled: false
  host: "umc-gateway.example.develop.souvap-univention.de"
  ingressClassName: "nginx"
  tls:
    enabled: false
