# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---
# Default values for univention-management-console-gateway
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Global values
affinity: {}
environment: {}
fullnameOverride: ""
mountUcr: true
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
tolerations: []

global:
  configMapUcrDefaults: "stack-data-ums-ucr"
  configMapUcr: "stack-data-swp-ucr"
  configMapUcrForced: null

# -- Application configuration of the Univention Management Console Gateway
umcGateway:
  umcHtmlTitle: null
  # -- The FQDN of the identity provider.
  # Example: `https://id.souvap.example.org`

## Kubernetes ingress
ingress:
  # -- Set this to `true` in order to enable the installation on Ingress related objects.
  enabled: true
  ingressClassName: "nginx"
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
  # -- The hostname. This parameter has to be supplied. Example `portal.example`.
  host: null
  # -- The path configuration. The default only grabs what is handled by the UMC gateway.
  paths:
    # TODO: Exact vs. Prefix
    - pathType: Exact
      path: /univention/languages.json
    - pathType: Exact
      path: /univention/meta.json
    - pathType: Exact
      path: /univention/theme.css
    - pathType: Prefix
      path: /univention/js/
    - pathType: Prefix
      path: /univention/login
    - pathType: Prefix
      path: /univention/management
    - pathType: Prefix
      path: /univention/self-service
    - pathType: Prefix
      path: /univention/themes/
  tls:
    enabled: true
    secretName: ""


## Istio support
istio:
  # -- Set this to `true` in order to enable the installation on Istio related objects.
  enabled: false
  # -- The hostname. This parameter has to be supplied. Example `portal.example`.
  host: null
  virtualService:
    enabled: true
    annotations: {}
    # -- The paths configuration.
    # The default only grabs what is known to be handled by the UMC gateway.
    paths:
      - match: "prefix"
        path: "/univention/js/"
        rewrite: "/univention/js/"
      - match: "prefix"
        path: "/univention/languages.json"
        rewrite: "/univention/languages.json"
      - match: "prefix"
        path: "/univention/login/"
        rewrite: "/univention/login/"
      - match: "prefix"
        path: "/univention/management/"
        rewrite: "/univention/management/"
      - match: "prefix"
        path: "/univention/self-service/"
        rewrite: "/univention/self-service/"
      - match: "prefix"
        path: "/univention/meta.json"
        rewrite: "/univention/meta.json"
      - match: "prefix"
        path: "/univention/theme.css"
        rewrite: "/univention/theme.css"
      - match: "prefix"
        path: "/univention/themes/"
        rewrite: "/univention/themes/"
  gateway:
    enabled: false
    annotations:
    selectorIstio: "ingressgateway"
    externalGatewayName: "swp-istio-gateway"
    tls:
      enabled: true
      httpsRedirect: true
      secretName: ""


## Docker image
image:
  registry: "gitregistry.knut.univention.de"
  repository: "univention/customers/dataport/upx/container-umc/umc-gateway"
  imagePullPolicy: "Always"
  tag: "latest"
  ## Define image sha256 as an alternative to `tag`
  # sha256:


## Container deployment probes
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 3
    periodSeconds: 30
    failureThreshold: 3
    successThreshold: 1

  readiness:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 3
    periodSeconds: 15
    failureThreshold: 30
    successThreshold: 1


## Deployment resources
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "4Gi"
    cpu: "4"


## Kubernetes Service
service:
  enabled: true
  type: "ClusterIP"
  ports:
    http:
      containerPort: 80
      port: 80
      protocol: "TCP"

  sessionAffinity:
    enabled: false
    timeoutSeconds: 10800

...
